apiVersion: v1
kind: Service
metadata:
  labels:
    run: wordpress-ad
  name: wordpress-ad
spec:
  clusterIP: 10.104.206.24
  clusterIPs:
  - 10.104.206.24
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30021
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: wordpress-ad
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
