apiVersion: v1
kind: Service
metadata:
  labels:
    run: mysql-ad
  name: mysql-ad
spec:
  clusterIP: 10.96.136.58
  clusterIPs:
  - 10.96.136.58
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql-ad
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
