apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-ad
  name: mysql-ad
spec:
  containers:
  - image: mysql:5.7
    name: mysql-ad
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_DATABASE
      value: exampledb
    - name: MYSQL_USER
      value: exampleuser
    - name: MYSQL_PASSWORD
      value: examplepass
    - name: MYSQL_RANDOM_ROOT_PASSWORD
      value: '1'
  dnsPolicy: ClusterFirst
  restartPolicy: Always