apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wordpress-ad
  name: wordpress-ad
spec:
  containers:
  - image: wordpress
    name: wordpress-ad
    ports:
    - containerPort: 8080
    env:
    - name: WORDPRESS_DB_HOST
      value: mysql
    - name: WORDPRESS_DB_USER
      value: exampleuser
    - name: WORDPRESS_DB_PASSWORD
      value: examplepass
    - name: WORDPRESS_DB_NAME
      value: exampledb    
  dnsPolicy: ClusterFirst
  restartPolicy: Always